name: "Is issue on a project board"
description: |
  This action will make a graphql query and determine whether an issue or pull request
  Is already added to the project board identified by the name of the board
inputs:
  token:
    description: "Github PAT with organization scope, e.g. secrets.GH_TOKEN"
    required: true
  owner:
    description: "The organization owns the board or repository"
    required: true
  board:
    description: "Project board name which should be searched for the Card with the issue"
    required: true
  number:
    description: "Issue or pull request number to look for"
    required: true
  repo:
    description: |
      the repo name (reponame in the owner scope without owner path)
      where the issue is located
    required: true
outputs:
  isOnBoard:
    description: "true if issue is added to the given board"
  boardId:
    description: node_id or graphql id of the board
  boardName: 
    description: name of teh project board
  repo:
    description: name of the repo where the issue is located
  cardId: 
    description: graphql id of the card
  columnName: 
    description: name of the column where the card with the issue is located
  columnId: 
    description: graphql id of the column where the card with the issue is located
runs:
  using: node16
  main: dist/index.js
